version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: webshop-web
        ports:
            - "8088:80"
        volumes:
            # Only mount specific directories for development
            # - ./app:/var/www/html/app
            # - ./config:/var/www/html/config
            # - ./public:/var/www/html/public
            # - ./Resources:/var/www/html/Resources
            - ./public/images:/var/www/html/public/images
        environment:
            DB_HOST: db
            DB_NAME: webshop_db
            DB_USER: webshopadmin
            DB_PASSWORD: '!webshopadmin2025'
            JWT_SECRET: ${JWT_SECRET:-your_default_jwt_secret_for_development}
            JWT_EXPIRY: ${JWT_EXPIRY:-86400}
            APP_ENV: development
            APP_DEBUG: 'true'
            NODE_ENV: production
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: mysql:8.0
        container_name: webshop-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: webshop_db
            MYSQL_USER: webshopadmin
            MYSQL_PASSWORD: '!webshopadmin2025'
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped

volumes:
    mysql_data:
