version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - ./public/images:/var/www/html/public/images
    environment:
      DB_HOST: db
      DB_NAME: webshop_db
      DB_USER: webshopadmin
      DB_PASSWORD: '!webshopadmin2025'
      JWT_SECRET: 'p8hsm4ckLs9EJnUxDwq2y76v3T5FbGjZ'
      JWT_EXPIRY: 86400
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db
    networks:
      - webshop-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webshop_db
      MYSQL_USER: webshopadmin
      MYSQL_PASSWORD: '!webshopadmin2025'
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - webshop-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  webshop-network:
    driver: bridge

volumes:
  mysql_data: